### ISSUE TITLE
Trouble with running PointSpritesExample.java

### ISSUE THREAD

**Issue by jfelrod1960** [Renanse/Ardor3D#106]
I'm getting this error when trying to execute the above mention code.  For now this is a question.  Do I need to update my drivers?  Or do I need to get a more advance graphics card?

Thanks
Jeff

[#version 330 core

out vec4 FragColor;

in vec4 DiffuseColor;

uniform sampler2D diffuse;

void main()
{
FragColor = vec4(texture2D(diffuse, gl_PointCoord)) * DiffuseColor;
}]
Throwable caught in MainThread - exiting
com.ardor3d.util.Ardor3dException: Error compiling Fragment shader: ERROR: 0:11: 'function' : is removed in Forward Compatible context texture2D
ERROR: 0:11: 'texture2D' : no matching overloaded function found (using implicit conversion) 
ERROR: 0:11: 'texture2D' : function is not known 

	at com.ardor3d.scene.state.lwjgl3.util.Lwjgl3ShaderUtils.prepareShader(Lwjgl3ShaderUtils.java:192)
	at com.ardor3d.scene.state.lwjgl3.util.Lwjgl3ShaderUtils.createShaderProgram(Lwjgl3ShaderUtils.java:89)
	at com.ardor3d.renderer.material.TechniquePass.startPass(TechniquePass.java:151)
	at com.ardor3d.renderer.material.TechniquePass.setupForDraw(TechniquePass.java:135)
	at com.ardor3d.scenegraph.Mesh.render(Mesh.java:287)
	at com.ardor3d.scenegraph.Mesh.render(Mesh.java:255)
	at com.ardor3d.scenegraph.Point.render(Point.java:173)
	at com.ardor3d.renderer.lwjgl3.Lwjgl3Renderer.draw(Lwjgl3Renderer.java:249)
	at com.ardor3d.scenegraph.Mesh.draw(Mesh.java:378)
	at com.ardor3d.renderer.queue.AbstractRenderBucket.render(AbstractRenderBucket.java:82)
	at com.ardor3d.renderer.queue.RenderQueue.renderBuckets(RenderQueue.java:110)
	at com.ardor3d.renderer.lwjgl3.Lwjgl3Renderer.renderBuckets(Lwjgl3Renderer.java:109)
	at com.ardor3d.renderer.lwjgl3.Lwjgl3Renderer.renderBuckets(Lwjgl3Renderer.java:102)
	at com.ardor3d.example.ExampleBase.renderExample(ExampleBase.java:296)
	at com.ardor3d.example.ExampleBase.render(ExampleBase.java:278)
	at com.ardor3d.framework.lwjgl3.Lwjgl3CanvasRenderer.draw(Lwjgl3CanvasRenderer.java:122)
	at com.ardor3d.framework.lwjgl3.GLFWCanvas.draw(GLFWCanvas.java:185)
	at com.ardor3d.framework.FrameHandler.updateFrame(FrameHandler.java:91)
	at com.ardor3d.example.ExampleBase.run(ExampleBase.java:147)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by Renanse** [comment]
No, actually, the shader embedded in the example's material YAML uses `texture2D`, which is outdated and should be replaced with just `texture`.  I've pushed up an update, so pull and give it another shot when you can.

**Comment by jfelrod1960** [comment]
Thanks Josh!  Working fine now.  Wishing you and your family the best this holiday season!

**Comment by Renanse** [comment]
Thanks!  You as well!
