### ISSUE TITLE
BMText throws exception when set to autorotate

### ISSUE THREAD

**Issue by thepowernap** [Renanse/Ardor3D#54]
When a BMText object is set to auto rotate, the following exception is occasionally  thrown.

JNA: Callback org.gstreamer.elements.BaseSink$1@1571f07 threw the following exception:
java.lang.RuntimeException: com.ardor3d.math.TransformException: Scale is already provided by 3x3 matrix.  If this is a mistake, consider using setRotation instead of setMatrix.
    at jogamp.opengl.GLRunnableTask.run(GLRunnableTask.java:65)
    at jogamp.opengl.GLDrawableHelper.execGLRunnables(GLDrawableHelper.java:628)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:568)
    at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:377)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1029)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:904)
    at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:568)
    at jogamp.opengl.GLDrawableHelper.invoke(GLDrawableHelper.java:724)
    at jogamp.opengl.GLAutoDrawableBase.invoke(GLAutoDrawableBase.java:515)
    at com.ardor3d.framework.jogl.JoglNewtWindow.draw(JoglNewtWindow.java:199)
    at com.kablab.vision.jogl.AugmentedRealityPlayer.update(AugmentedRealityPlayer.java:565)
    at com.kablab.vision.jogl.GstGLComponent$RGBListener.rgbFrame(GstGLComponent.java:281)
    at com.kablab.vision.VideoDataSink$VideoHandoffListener.doHandoff(VideoDataSink.java:170)
    at com.kablab.vision.VideoDataSink$VideoHandoffListener.handoff(VideoDataSink.java:146)
    at org.gstreamer.elements.BaseSink$1.callback(BaseSink.java:137)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:444)
    at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:474)
Caused by: com.ardor3d.math.TransformException: Scale is already provided by 3x3 matrix.  If this is a mistake, consider using setRotation instead of setMatrix.
    at com.ardor3d.math.Transform.setScale(Transform.java:250)
    at com.ardor3d.math.ValidatingTransform.setScale(ValidatingTransform.java:80)
    at com.ardor3d.math.ValidatingTransform.setScale(ValidatingTransform.java:1)
    at com.ardor3d.ui.text.BMText.correctTransform(BMText.java:327)
    at com.ardor3d.ui.text.BMText.draw(BMText.java:307)
    at com.ardor3d.renderer.queue.TransparentRenderBucket.render(TransparentRenderBucket.java:104)
    at com.ardor3d.renderer.queue.RenderQueue.renderBuckets(RenderQueue.java:132)
    at com.ardor3d.renderer.jogl.JoglRenderer.renderBuckets(JoglRenderer.java:144)
    at com.ardor3d.renderer.jogl.JoglRenderer.renderBuckets(JoglRenderer.java:137)
    at com.ardor3d.renderer.jogl.JoglRenderer.flushFrame(JoglRenderer.java:222)
    at com.ardor3d.framework.jogl.JoglCanvasRenderer.draw(JoglCanvasRenderer.java:256)
    at com.ardor3d.framework.jogl.JoglDrawerRunnable.run(JoglDrawerRunnable.java:16)
    at jogamp.opengl.GLRunnableTask.run(GLRunnableTask.java:59)
    ... 19 more

commenting out the section of code that throws the exception causes no problems aside from the BMText resizing for a frame, then returning to normal

in class com.ardor3d.math.Transform

public Transform setScale(final ReadOnlyVector3 scale) {
        //---Comment this section out to work----
        // if (!_rotationMatrix) {
        // throw new TransformException(
        // "Scale is already provided by 3x3 matrix.  If this is a mistake, consider using setRotation instead of setMatrix.");
        // }
        //---End Hack---
        if (scale.getX() == 0.0 && scale.getY() == 0.0 && scale.getZ() == 0.0) {
            throw new IllegalArgumentException("scale may not be ZERO.");
        }

```
    _scale.set(scale);
    _identity = _identity && scale.getX() == 1.0 && scale.getY() == 1.0 && scale.getZ() == 1.0;
    _uniformScale = scale.getX() == scale.getY() && scale.getY() == scale.getZ();
    return this;
}
```

**Comment by Renanse** [comment]
I was not able to repro and this is quite old, so closing
