### ISSUE TITLE
Can't run examples.

### ISSUE THREAD

**Issue by Nirzvi1** [Renanse/Ardor3D#74]
I installed Ardor3D using: https://github.com/Renanse/Ardor3D/wiki/Getting-started-with-Git-and-Eclipse.
When I try to run ExampleRunner, I get this error message in the console: 

<pre>Exception in thread "main" java.lang.NoClassDefFoundError: com/ardor3d/example/ExampleRunner
Caused by: java.lang.ClassNotFoundException: com.ardor3d.example.ExampleRunner
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)</pre>

Please help!

**Comment by gouessej** [comment]
You already asked this question here: http://stackoverflow.com/questions/30293042/installing-ardor3d-i-cant-even-run-the-examples

**Comment by Nirzvi1** [comment]
I did, and I was told to post my question here.
