### ISSUE TITLE
Error running ShadowedTerrainExample

### ISSUE THREAD

**Issue by jfelrod1960** [Renanse/Ardor3D#97]
Hey Josh,

I got the following error:

Throwable caught in MainThread - exiting
com.ardor3d.util.Ardor3dException: Error compiling Fragment shader: ERROR: 0:214: '=' : assigning non-constant to 'const highp float'
ERROR: 0:215: '=' : assigning non-constant to 'const highp float'
ERROR: 0:231: '=' : assigning non-constant to 'const highp float'
ERROR: 0:232: '=' : assigning non-constant to 'const highp float'
ERROR: 0:249: '=' : assigning non-constant to 'const highp float'

	at com.ardor3d.scene.state.lwjgl3.util.Lwjgl3ShaderUtils.prepareShader(Lwjgl3ShaderUtils.java:191)
	at com.ardor3d.scene.state.lwjgl3.util.Lwjgl3ShaderUtils.createShaderProgram(Lwjgl3ShaderUtils.java:88)
	at com.ardor3d.renderer.material.TechniquePass.startPass(TechniquePass.java:151)
	at com.ardor3d.renderer.material.TechniquePass.setupForDraw(TechniquePass.java:135)
	at com.ardor3d.scenegraph.Mesh.render(Mesh.java:287)
	at com.ardor3d.scenegraph.Mesh.render(Mesh.java:255)
	at com.ardor3d.renderer.lwjgl3.Lwjgl3Renderer.draw(Lwjgl3Renderer.java:249)
	at com.ardor3d.scenegraph.Mesh.draw(Mesh.java:378)
	at com.ardor3d.renderer.queue.AbstractRenderBucket.render(AbstractRenderBucket.java:82)
	at com.ardor3d.renderer.queue.RenderQueue.renderBuckets(RenderQueue.java:110)
	at com.ardor3d.renderer.lwjgl3.Lwjgl3Renderer.renderBuckets(Lwjgl3Renderer.java:109)
	at com.ardor3d.renderer.lwjgl3.Lwjgl3Renderer.renderBuckets(Lwjgl3Renderer.java:102)
	at com.ardor3d.example.ExampleBase.renderExample(ExampleBase.java:296)
	at com.ardor3d.example.ExampleBase.render(ExampleBase.java:278)
	at com.ardor3d.framework.lwjgl3.Lwjgl3CanvasRenderer.draw(Lwjgl3CanvasRenderer.java:122)
	at com.ardor3d.framework.lwjgl3.GLFWCanvas.draw(GLFWCanvas.java:179)
	at com.ardor3d.framework.FrameHandler.updateFrame(FrameHandler.java:91)
	at com.ardor3d.example.ExampleBase.run(ExampleBase.java:147)
	at java.base/java.lang.Thread.run(Thread.java:834)

Hope all is well with you
Jeff

**Comment by Renanse** [comment]
Thanks for the report.  Definitely need more folks trying on a variety of cards.  I've pushed a possible fix.  Could you try that?

**Comment by jfelrod1960** [comment]
Looks good Josh!!!  Thanks!
